---
title: "Twitter break"
author: Karl
date: '2018-10-05'
slug: twitter-break
categories: [twitter]
tags: [twitter]
---

What I've liked most about Twitter is that it's helped me to feel less
isolated, as I've been able to connect with distant folks who share my
interests and values, particularly regarding open science and
reproducible reearch.

But somehow, lately, Twitter had me feeling less rather than more
connected. I think maybe it's been that conference effect: scientific
conferences are great for catching up with old friends and seeing all
of the cool things that everyone's doing, but ultimately they often
leave me feeling like crap because everyone else seems to be doing
cool and exciting stuff while I gave a talk on the same old stuff I've
been working on for five years with little apparent progress.

So I took a two-month break from Twitter. But I can't say that I
really felt better for it. And going back I see I've missed like 100
tweets about my [paper](https://doi.org/10.1080/00031305.2017.1375989)
with [Kara Woo](https://twitter.com/kara_woo) on [data organization in
spreadsheets](https://doi.org/10.1080/00031305.2017.1375989). And I
was mentioned among [UW-Madison's most interesting Twitter
acccounts](https://news.wisc.edu/uws-most-interesting-twitter-accounts-you-need-to-follow/).

So I'm coming back to Twitter, but maybe in a more scaled-back way.
