---
title: "reproducibility guidelines"
author: Karl
date: '2019-04-01'
slug: reproducibility-guidelines
categories: [academics]
tags: [reproducible research]
---

I'm in Delft, The Netherlands, for a few days this week, at a
[workshop](https://o2r.info/reproducible-agile/initiative/) to develop
guidelines for reproducibility for
[AGILE](https://agile-online.org/) conference papers. I'm here as one of the
outside
"[experts](https://o2r.info/reproducible-agile/initiative/#expert-meeting)".
(It's always a bit disconcerting to be considered an expert.) The
[leaders of this
effort](https://o2r.info/reproducible-agile/initiative/#initiative-members)
wrote an interesting [PeerJ paper](https://doi.org/10.7717/peerj.5072)
last year, evaluating the reproducibility of previous AGILE papers.

There will be a [community
webinar](https://o2r.info/reproducible-agile/initiative/#community-webinar)
tomorrow (2019-04-02) at [16:00
CEST](https://www.timeanddate.com/worldclock/meetingdetails.html?year=2019&month=4&day=2&hour=14&min=0&sec=0&p1=16)
(which is 9:00am US central daylight time), to report our initial
thoughts and get community feedback.

I'm particularly interested in developing these guidelines and using
what I learn to further reproduciblity of work published in the
journals [Genetics](https://academic.oup.com/genetics) and
[G3](https://academic.oup.com/g3journal). These journals have been doing a great
job of enforcing their policy that data be made publicly available. They've
also had a policy that software be made available, but there has not
been much effort to enforce that, and it's clear that many authors need
further pressure (or _encouragement_) before they will comply.

I've done a better job with reproducibility of my recent
papers (about [R/qtl2](https://github.com/kbroman/Paper_Rqtl2) and
[genotype diagnostics](https://github.com/kbroman/Paper_MPPdiag)), but
it remains a challenge to keep things well-organized and well-documented.

Regarding these reproducibility guidelines, I
think authors will benefit from very specific suggestions that can
accommodate different levels of computational "sophistication." And I
think what will be particularly helpful will be a variety of specific
examples that authors might use as templates. I've been impressed with
the care that [Will Valdar](https://valdarlab.unc.edu)'s group has been
devoting to reproducibility. For example, the [recent paper by Shorter
et al.](https://doi.org/10.1534/g3.118.200847) is
accompanied by a proper [R Compendium](https://github.com/mauriziopaul/litterDiallel).
Will's student [Roberty Corty](https://github.com/rcorty/) has github
repositories for his recent papers on variance QTL, including
[this](https://github.com/rcorty/qtl_mapping_with_BVH_supporting_files)
and [that](https://github.com/rcorty/mvqtl_reanalyses_Bailey_Kumar_supporting_files).
